Added INI support

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -6,19 +6,16 @@ SCRIPT=$(readlink -f "$0")
 SCRIPTPATH=$(dirname "$SCRIPT")
 #http://stackoverflow.com/questions/242538/unix-shell-script-find-out-which-directory-the-script-file-resides
 
-# Get the config variables
-source ${SCRIPTPATH}/manager-config.sh
-# Just incase, I already made the mistake of creating the file in windows....
-MAX_PLAYERS=`echo ${MAX_PLAYERS} | sed -e 's/\r//g'`
-GALAXY=`echo ${GALAXY} | sed -e 's/\r//g'`
-PARAMS=`echo ${PARAMS} | sed -e 's/\r//g'`
-PORT=`echo ${PORT} | sed -e 's/\r//g'`
-LOG_ROTATION=`echo ${LOG_ROTATION} | sed -e 's/\r//g'`
-AutoRestart=`echo ${AutoRestart} | sed -e 's/\r//g'`
-DAILYRESTART=`echo ${DailyRestart} | sed -e 's/\r//g'`
-BETA=`echo ${BETA} | sed -e 's/\r//g'`
-PHPPORT=`echo ${PHPPORT} | sed -e 's/\r//g'`
-
+#Pull values from config INI
+MAX_PLAYERS=$(awk -F "=" '/MAX_PLAYERS/ {print $2}' manager-config.ini)
+GALAXY=$(awk -F "=" '/GALAXY/ {print $2}' manager-config.ini)
+PARAMS=$(awk -F "=" '/PARAMS/ {print $2}' manager-config.ini)
+PORT=$(awk -F "=" '/PORT/ {print $2}' manager-config.ini)
+LOG_ROTATION=$(awk -F "=" '/LOG_ROTATION/ {print $2}' manager-config.ini)
+AutoRestart=$(awk -F "=" '/AutoRestart/ {print $2}' manager-config.ini)
+DAILYRESTART=$(awk -F "=" '/DAILYRESTART/ {print $2}' manager-config.ini)
+BETA=$(awk -F "=" '/BETA/ {print $2}' manager-config.ini)
+PHPPORT=$(awk -F "=" '/PHPPORT/ {print $2}' manager-config.ini)
 # Standard Config - Dont touch
 TMUX_SESSION=avoriontmux
 INSTALL_DIR=$SCRIPTPATH/serverfiles
@@ -108,7 +105,8 @@ case $1 in
 			if pidof ${SERVER} > /dev/null;
 			then
         DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} has started with pid ${YELLOW}$(pidof ${SERVER})${NOCOLOR}" "${RUN_BY}"
-        VER=`wget -O - -o /dev/null https://raw.githubusercontent.com/dirtyredz/Dirty-Server-Manager/master/VERSION`
+        DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} has started with params: ${PARAMS}" "${RUN_BY}"
+        VER=`wget -O - -o /dev/null https://api.github.com/repos/dirtyredz/Dirty-Server-Manager/releases/latest | grep tag_name | sed -e 's/.*://g' -e 's/"//g' -e 's/,//g' | tr -d '[:blank:]'`
         if [ "${VER}" != "${VERSION}" ]; then
           DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} Dirty Server Manager is NOT Up To Date!" "${RUN_BY}"
         else
@@ -141,6 +139,7 @@ case $1 in
       $T /save C-m
       time=0
       while [ $time -lt 60 ]; do
+
         PlayerMemory=$(cat ${SCRIPTPATH}'/console.log' | awk "/${D}/,/All sectors saved successfully/" | grep 'All sectors saved successfully')
         if [ "${PlayerMemory}" ]; then
           break;
@@ -168,7 +167,10 @@ case $1 in
       done
       DynamicEcho "\r" "${RUN_BY}" "DONTLOG"
       DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} is being forcibly closed! Just incase." "${RUN_BY}"
-      kill $(pidof ${SERVER})
+      if ! kill $(pidof ${SERVER}) > /dev/null 2>&1; then
+        DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} Could not send SIGTERM to Server Process." "${RUN_BY}"
+      fi
+      tmux kill-session -t ${TMUX_SESSION}
     else
       DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} is not running currently!" "${RUN_BY}"
 		fi
@@ -202,18 +204,23 @@ case $1 in
 	"restart")
     LogToManagerLog "Ran Restart command.";
 		DynamicEcho "restarting ${PURPLE}${SERVER}${NOCOLOR}..." "${RUN_BY}"
+    OLDPID=$(pidof ${SERVER})
 		$0 stop "${RUN_BY}"
     sleep 60
 		$0 start "${RUN_BY}"
+    NEWPID=$(pidof ${SERVER})
     time=0
     #First Try
     while [ $time -lt 30 ]; do
-      if pidof ${SERVER} > /dev/null
-  		then
+      if [ pidof ${SERVER} > /dev/null ] && [ OLDPID != NEWPID ]; then
         DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} has successfully restarted!" "${RUN_BY}"
         exit 1
       else
         DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} attempting restart of the server." "${RUN_BY}"
+        if ! kill $(pidof ${SERVER}) > /dev/null 2>&1; then
+          DynamicEcho "${PURPLE}${SERVER}${NOCOLOR} Could not send SIGTERM to Server Process." "${RUN_BY}"
+        fi
+        tmux kill-session -t ${TMUX_SESSION}
         $0 start "${RUN_BY}"
       fi
       let time++
@@ -379,8 +386,6 @@ case $1 in
     then
       DynamicEcho "starting PHP Server"
 
-      #Z='tmux send-keys -t 'php':0.0'
-      #$Z 'php -S '"${IPADDRESS}"':'"${PHPPORT}"' -t '${SCRIPTPATH}'/avorion-manager/webroot' C-m
       if pidof php > /dev/null;
       then
         DynamicEcho "PHP Server started on server: http://${IPADDRESS}"':'"${PHPPORT}"
@@ -473,28 +478,26 @@ case $1 in
     fi
     echo Auto Daily Restart: $DailyRestartInput
 
-    read -p "Admin steam id: [Y/n]"  AdminInput
+    read -p "Admin steam id:"  AdminInput
     AdminInput=${AdminInput}
     echo Admin Steam ID: $AdminInput
     AdminInput=" --admin ${AdminInput}"
 
     echo "Completed manager configuration, to make changes to these settings in the future edit file manager-config.sh"
     read -p "Press enter to continue with steam/avorion installation"
-    echo "#!/bin/bash" > manager-config.sh
-    echo "# Config" >> manager-config.sh
-    echo "MAX_PLAYERS=${MaxPlayersInput}" >> manager-config.sh
-    echo "GALAXY=${GalaxyNameInput}" >> manager-config.sh
-    echo "PARAMS='--public ${PublicServerInput} --listed ${ListedServerInput} --same-start-sector ${SameStartInput}${AdminInput}' # http://wiki.avorion.net/index.php?title=Server" >> manager-config.sh
-    echo "# Standard Config" >> manager-config.sh
-    echo "PORT=${PortInput}" >> manager-config.sh
-    echo "# Auto Restart" >> manager-config.sh
-    echo "LOG_ROTATION=10 #Days to keep status.logs" >> manager-config.sh
-    echo "AutoRestart=${AutoCrashRestartInput} #If the status check that runs every 5 minutes fails to get a response from the server it will automatically issue a restart command" >> manager-config.sh
-    echo "DailyRestart=${DailyRestartInput} #Will restart the server at the MIDNIGHT and NOON SERVER time." >> manager-config.sh
-    echo "# Installation" >> manager-config.sh
-    echo "BETA=${BetaInput}" >> manager-config.sh
-    echo "# PHP" >> manager-config.sh
-    echo "PHPPORT=8080" >> manager-config.sh
+    echo "MAX_PLAYERS=${MaxPlayersInput}" >> manager-config.ini
+    echo "GALAXY=${GalaxyNameInput}" >> manager-config.ini
+    echo ";http://wiki.avorion.net/index.php?title=Server"
+    echo "PARAMS='--public ${PublicServerInput} --listed ${ListedServerInput} --same-start-sector ${SameStartInput}${AdminInput}'" >> manager-config.ini
+    echo "PORT=${PortInput}" >> manager-config.ini
+    echo ";Days to keep status.logs" >> manager-config.ini
+    echo "LOG_ROTATION=10" >> manager-config.ini
+    echo ";If the status check that runs every 5 minutes fails to get a response from the server it will automatically issue a restart command" >> manager-config.ini
+    echo "AutoRestart=${AutoCrashRestartInput}" >> manager-config.ini
+    echo ";Will restart the server at the MIDNIGHT and NOON SERVER time." >> manager-config.ini
+    echo "DailyRestart=${DailyRestartInput}" >> manager-config.ini
+    echo "BETA=${BetaInput}" >> manager-config.ini
+    echo "PHPPORT=8080" >> manager-config.ini
 
     mkdir -p $STEAM_DIR
     wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
